title: The Wordsmith Weekly
author: Kayce Basques
email: kaycebasques@gmail.com
baseurl: ""
url: "https://wordsmithweekly.com"
twitter_username: kaycebasques
github_username: kaycebasques
description: "The technical writing blog of Kayce Basques."

# Build settings
markdown: kramdown
source: src
exclude: [sw.js] # caution: relative to source directory
keep_files: [sw.js, workbox-sw.prod.v1.0.1.js, workbox-sw.prod.v1.0.1.js.map]
