# Accessible in pages via { site.title }
title: The Wordsmith Weekly
author: Kayce Basques
email: kaycebasques@gmail.com

# Build settings
markdown: kramdown
source: src
exclude: [sw.js] # caution: relative to source directory
keep_files: [sw.js, workbox-sw.prod.v1.0.1.js, workbox-sw.prod.v1.0.1.js.map]
destination: build/jekyll
